[package]
name = "echidna"
version = "0.1.0"
edition = "2021"

[dependencies]
compiler_builtins = { version = "0.1.139", features = ["mem"] }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
